// backendbhai.preload.mjs
// Auto-generated by `npx backendbhai init`.
//
// This file is loaded via `node --import ./backendbhai.preload.mjs` BEFORE any
// other code. It patches http, express, pg, redis etc. so that every request
// and query is captured as an OpenTelemetry trace and sent to BackendBhai.
//
// ✏️  Customize SERVICE_NAME below or set it as an environment variable.

import pkgNodeSDK from '@opentelemetry/sdk-node';
const { NodeSDK } = pkgNodeSDK;

import pkgExporter from '@opentelemetry/exporter-trace-otlp-http';
const { OTLPTraceExporter } = pkgExporter;

import pkgAuto from '@opentelemetry/auto-instrumentations-node';
const { getNodeAutoInstrumentations } = pkgAuto;

import pkgResources from '@opentelemetry/resources';
const { Resource } = pkgResources;

import pkgSemantic from '@opentelemetry/semantic-conventions';
const { ATTR_SERVICE_NAME, ATTR_SERVICE_VERSION } = pkgSemantic;

const serviceName = process.env.SERVICE_NAME || '{{SERVICE_NAME}}';
const otlpEndpoint = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || 'http://localhost:4318';

const sdk = new NodeSDK({
  resource: new Resource({
    [ATTR_SERVICE_NAME]: serviceName,
    [ATTR_SERVICE_VERSION]: '1.0.0',
  }),
  traceExporter: new OTLPTraceExporter({
    url: `${otlpEndpoint}/v1/traces`,
  }),
  instrumentations: [
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-express': { enabled: true },
      '@opentelemetry/instrumentation-http':    { enabled: true },
      '@opentelemetry/instrumentation-pg':      { enabled: true },
      '@opentelemetry/instrumentation-redis':   { enabled: true },
      '@opentelemetry/instrumentation-mongodb': { enabled: true },
      '@opentelemetry/instrumentation-fs':      { enabled: false },
    }),
  ],
});

sdk.start();
console.log(`[BackendBhai] Tracing "${serviceName}" → ${otlpEndpoint}`);

process.on('SIGTERM', async () => { await sdk.shutdown(); process.exit(0); });
process.on('SIGINT',  async () => { await sdk.shutdown(); process.exit(0); });
